//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolFacilityReport.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolFacilityReport.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Notes.
        /// </summary>
        public static string AdminNotesTitle {
            get {
                return ResourceManager.GetString("AdminNotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am Maintenance Team.
        /// </summary>
        public static string AdminRole {
            get {
                return ResourceManager.GetString("AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenence Jobs.
        /// </summary>
        public static string AdminTitle {
            get {
                return ResourceManager.GetString("AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC/Fan.
        /// </summary>
        public static string Cat_AC {
            get {
                return ResourceManager.GetString("Cat_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical.
        /// </summary>
        public static string Cat_Elec {
            get {
                return ResourceManager.GetString("Cat_Elec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture.
        /// </summary>
        public static string Cat_Furn {
            get {
                return ResourceManager.GetString("Cat_Furn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Cat_Other {
            get {
                return ResourceManager.GetString("Cat_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plumbing.
        /// </summary>
        public static string Cat_Plumb {
            get {
                return ResourceManager.GetString("Cat_Plumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescLabel {
            get {
                return ResourceManager.GetString("DescLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the damage....
        /// </summary>
        public static string DescPlaceholder {
            get {
                return ResourceManager.GetString("DescPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My History.
        /// </summary>
        public static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string LevelLabel {
            get {
                return ResourceManager.GetString("LevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Location.
        /// </summary>
        public static string LocationBtn {
            get {
                return ResourceManager.GetString("LocationBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixIt@Campus.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Details.
        /// </summary>
        public static string PageTitle_JobDetails {
            get {
                return ResourceManager.GetString("PageTitle_JobDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string PageTitle_Login {
            get {
                return ResourceManager.GetString("PageTitle_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        public static string PhotoBtn {
            get {
                return ResourceManager.GetString("PhotoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register (New Account).
        /// </summary>
        public static string RegisterBtn {
            get {
                return ResourceManager.GetString("RegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issue.
        /// </summary>
        public static string ReportTitle {
            get {
                return ResourceManager.GetString("ReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are you?.
        /// </summary>
        public static string RoleTitle {
            get {
                return ResourceManager.GetString("RoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string StatusInProgress {
            get {
                return ResourceManager.GetString("StatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved.
        /// </summary>
        public static string StatusResolved {
            get {
                return ResourceManager.GetString("StatusResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Status.
        /// </summary>
        public static string StatusUpdateTitle {
            get {
                return ResourceManager.GetString("StatusUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a Student / Staff.
        /// </summary>
        public static string StudentRole {
            get {
                return ResourceManager.GetString("StudentRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Report.
        /// </summary>
        public static string SubmitBtn {
            get {
                return ResourceManager.GetString("SubmitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgency.
        /// </summary>
        public static string UrgencyLabel {
            get {
                return ResourceManager.GetString("UrgencyLabel", resourceCulture);
            }
        }
    }
}
